package com.example.calculator

const val NUMBER_0: String = "0"
const val NUMBER_1: String = "1"
const val NUMBER_2: String = "2"
const val NUMBER_3: String = "3"
const val NUMBER_4: String = "4"
const val NUMBER_5: String = "5"
const val NUMBER_6: String = "6"
const val NUMBER_7: String = "7"
const val NUMBER_8: String = "8"
const val NUMBER_9: String = "9"
const val OPERATOR: String = ""
const val OPERATOR_ADD: String = "+"
const val OPERATOR_SUB: String = "-"
const val OPERATOR_MUL: String = "x"
const val OPERATOR_DIV: String = ":"
const val OPERATOR_EQUAL: String = "="
const val OPERATOR_AC: String = "ac"